name: CI
on:
  push:
    branches:
    - main
    - test-sdkman
    tags:
    - "v*"
  pull_request:

jobs:

  generate-native-launchers:
    name: Upload native launcher ${{ matrix.OS }}
#    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: 8
#      - name: Copy artifacts
#        run: .github/scripts/maybe-with-graalvm-home.sh copyLauncher artifacts/
#        shell: bash
      - name: Build OS packages
        run: .github/scripts/generate-os-packages.sh
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2


